### ISSUE TITLE
Rocket Jumping Gamemode

### ISSUE THREAD

**Issue by Gocnak** [momentum-mod/game#347]
Alright, since @laurirasanen set us up for RJ to be in Momentum much sooner than 1.0.0, we can begin to explore adding the features specific to the game mode.

## Things to be done by 0.8.2:
- [x] Rocket launcher with correct speed/damage values (thanks @laurirasanen !)
- [x] Give the rocket launcher on spawn by default
- [x] Mount TF2 assets for maps that use them
- [x] Zone changes
    - [x] Start only on zone exit
    - [x] Do not limit speed inside the zone
- [ ] Missing entities
    - [x] info_player_teamspawn (match with info_player_terrorist/counterterrorist)
    - [x] [func_nogrenades](https://github.com/VSES/SourceEngine2007/blob/master/se2007/game/server/tf/func_nogrenades.cpp)
    - [ ] Entities that can be removed from maps:
        - [ ] func_regenerate (players are invulnerable)
        - [ ] trigger_capture_area (maps to the stop trigger most times)
        - [ ] team_control_point (see above)
        - [ ] team_control_point_master (see above) [may just have been needed entities for ending the map]
        - [ ] func_nobuild (there's no engineer class in this game)
- [x] Movement changes
    - [x] Player origin should go up more when crouching midair
    - [x] Landing on the floor should stop the player very quickly (horizontal velocity gets clamped to 240 during the next WalkMove)
    - [x] [Ducking should take 0.2 seconds instead of 0.4](https://github.com/momentum-mod/game/blob/develop/mp/src/game/shared/shareddefs.h#L105-L110)
    - [x] C-taps
  - [x] Rocketjumping in shallow water should give extra speed
  - [x] Gamemode-protect the fix to hovering 2-units above the ground to allow bounces in RJ
- [x] Bugfixes
    - [x] Rockets can be fired through walls if player is hugging the wall and facing a specific angle
    - [x] Speed gained from rockets should be lower, something funky is going on here

## Things to do any time, can be after 0.8.2:
(Move the remaining to their own card after if/when this is closed)
- [x] Deterring abuse
  - [x] Prevent players from firing rockets and teleporting to the start zone (but allow it if the map does) for an easy stack. (Delete the rockets if there is no map-specific zone for it?)
- [x] Weapons
  - [ ] Shotgun with correct fixed spread (moved to #402 )
  - [ ] Sticky launcher with correct damage/limits (moved to #403 )
  - [x] Alternate firing modes for rocket:
      - [x] Center firing
      - [x] Left-handed firing
  - [x] Melee weapon (not super useful but can be used to punch some buttons) => use weapon_knife
- [ ] Quality of life things
  - [ ] Toggling HL2/TF2 sounds, and whether they are on/off (moved to #400 )
  - [ ] Toggling explosion effects, rocket trails, particles, etc. (moved to #400 )
  - [x] Correct weapon slots for Rocket Launcher and Shotgun (buckets 0 and 1 respectively if we want to align with TF2)
  - [ ] Toggling hitmarkers (moved to #399 )

RNG things to consider:
[Speedshots](https://jump.tf/forum/index.php?topic=1223.0)
[RNG bhops](https://jump.tf/forum/index.php?topic=2520.0)
[Bounces](https://www.youtube.com/watch?v=fSpHs0yWeCQ)
